variables:
  POSTGRES_DB: db_myerp
  POSTGRES_USER: usr_myerp
  POSTGRES_PASSWORD: myerp

cache:
  paths:
    - /root/.m2/repository

stages:
  - build
  - test
  
    
build-job:
  image:  maven:3.6.3-openjdk-8
  stage: build
  script:
    - echo \" BUILD\"
    - mvn compile -f src


test-business:
  image:  maven:3.6.3-openjdk-8
  services:
    - postgres:9.4
  stage: test
  script:
    - echo \" TEST-BUSINESS\"
    - mvn  verify -f src -P test-business

test-consumer:
  image:  maven:3.6.3-openjdk-8
  services:
    - postgres:9.4
  stage: test
  script:
    - echo \" TEST-CONSUMER\"
    - mvn verify -f src -P test-consumer
