language: java

dist: xenial

services:
  - docker
  

before_script:
  - cd docker/dev
  - docker-compose up -d 
  - cd ../..

script:
  - mvn compile -f src
  - mvn verify -f src sonar:sonar -P test-business -Dsonar.login=791155cb746dcaed7e8c2b389f083f3c8718e859
  - mvn verify -f src sonar:sonar -P test-consumer -Dsonar.login=791155cb746dcaed7e8c2b389f083f3c8718e859
  
