language: java

dist: xenial

services:
  - docker
  

before_script:
  - cd docker/dev
  - docker-compose up -d 
  - cd ../..

script:
  - mvn compile -f src
  - mvn verify -f src sonar:sonar -P test-business -Dsonar.login=$SONAR_TOKEN
  - mvn verify -f src sonar:sonar -P test-consumer -Dsonar.login=$SONAR_TOKEN
