language: java

dist: xenial

services:
  - docker
  

before_script:
  - cd docker/dev
  - docker-compose up -d 
  - cd ../..

jobs:
  include:
    - stage: build
      script:
        - mvn compile -f src

    - stage: test
      name: "test-business"
      script:
        - mvn verify -f src sonar:sonar -P test-business -Dsonar.login=d822f9f5c03372f73356aef9cc9207a02519278b
    - stage: test
      name: "test-consumer"
      script:
        - mvn verify -f src sonar:sonar -P test-consumer -Dsonar.login=d822f9f5c03372f73356aef9cc9207a02519278b
